apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels:
    service: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    service: postgres
